import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              window._AMapSecurityConfig = {
                securityJsCode: '${process.env.NEXT_PUBLIC_AMAP_SECURITY_KEY}',
              };
            `,
          }}
        ></script>
        <script
          type="text/javascript"
          src={`https://webapi.amap.com/maps?v=2.0&key=${process.env.NEXT_PUBLIC_AMAP_KEY}`}
        ></script>
      </head>
      <body suppressHydrationWarning={true}>
        <Header />
        <main className="pt-16">{children}</main>
      </body>
    </html>
  );
}